@startuml SSD_PERFORMANCE_DELETE
    title SSD_PERFORMANCE_DELETE
    hide footbox
    Actor "Admin" as A
    Participant "Systeme" as S
    S -> A : display confirmation page
    alt
    A -> S : click confirm button
    S -> S : delete
    S -> S : delete related reservations
    else
    A -> S : click cancel button
    end
    ref over A,S : SSD_PERFORMANCE_LIST
@enduml