@startuml SSD_PERFORMANCE_CREATE
    title SSD_PERFORMANCE_CREATE
    hide footbox
    Actor "Admin" as A
    Participant "Systeme" as S


    S -> A : display create page
    
    A -> S : give beginDate 
    A -> S : give endDate
    A -> S : give frequency
    A -> S : give theater

    alt
    A -> S : click confirm button
    S -> S : create
    else
    A -> S : click cancel button
    end
    ref over A,S : SSD_PERFORMANCE_LIST
@enduml